from __future__ import annotations

DOWNLOAD_STATUS_SUCCESS = "SUCCESS"
DOWNLOAD_STATUS_FAILED = "FAILED"
DOWNLOAD_STATUS_SKIPPED = "SKIPPED"
DOWNLOAD_STATUS_RESUMABLE = "RESUMABLE"

RUN_MODE_INCREMENTAL = "incremental"
RUN_MODE_FULL = "full"

DEFAULT_CHUNK_SIZE_BYTES = 4 * 1024 * 1024
