from __future__ import annotations

# --- Download status ---
DOWNLOAD_STATUS_SUCCESS = "SUCCESS"
DOWNLOAD_STATUS_FAILED = "FAILED"
DOWNLOAD_STATUS_SKIPPED = "SKIPPED"
DOWNLOAD_STATUS_RESUMABLE = "RESUMABLE"
DOWNLOAD_STATUS_UNKNOWN = "UNKNOWN"

# --- Person roles ---
PERSON_ROLE_CREATOR = "CREATOR"
PERSON_ROLE_CONTRIBUTOR = "CONTRIBUTOR"
PERSON_ROLE_SUPERVISOR = "SUPERVISOR"
PERSON_ROLE_OTHER = "OTHER"
PERSON_ROLE_UNKNOWN = "UNKNOWN"

# --- Download methods ---
DOWNLOAD_METHOD_API = "API-CALL"
DOWNLOAD_METHOD_SCRAPING = "SCRAPING"

# --- Repository IDs (from Qualitative Data Repositories list) ---
REPO_ID_ZENODO = 1
REPO_ID_DRYAD = 2
REPO_ID_UK_DATA_SERVICE = 3
REPO_ID_SYRACUSE_QDR = 4
REPO_ID_DANS = 5
REPO_ID_DATAVERSE_NO = 6
REPO_ID_ADA = 7
REPO_ID_SADA = 8
REPO_ID_HIHSN = 9
REPO_ID_HARVARD_DATAVERSE = 10

# --- Run modes ---
RUN_MODE_INCREMENTAL = "incremental"
RUN_MODE_FULL = "full"

DEFAULT_CHUNK_SIZE_BYTES = 4 * 1024 * 1024
