from __future__ import annotations

# --- Download status (final, persisted values per schema spec) ---
DOWNLOAD_STATUS_SUCCESS = "SUCCEEDED"
DOWNLOAD_STATUS_FAILED = "FAILED_SERVER_UNRESPONSIVE"
DOWNLOAD_STATUS_FAILED_LOGIN_REQUIRED = "FAILED_LOGIN_REQUIRED"
DOWNLOAD_STATUS_FAILED_TOO_LARGE = "FAILED_TOO_LARGE"

# Transient (in-memory only) statuses used during a run; sinks map these
# to a final value before persisting (transient → FAILED_SERVER_UNRESPONSIVE
# on new rows, preserve existing status on conflict).
DOWNLOAD_STATUS_SKIPPED = "SKIPPED"
DOWNLOAD_STATUS_RESUMABLE = "RESUMABLE"
DOWNLOAD_STATUS_UNKNOWN = "UNKNOWN"

DOWNLOAD_STATUS_FINAL = frozenset(
    {
        DOWNLOAD_STATUS_SUCCESS,
        DOWNLOAD_STATUS_FAILED,
        DOWNLOAD_STATUS_FAILED_LOGIN_REQUIRED,
        DOWNLOAD_STATUS_FAILED_TOO_LARGE,
    }
)
DOWNLOAD_STATUS_TRANSIENT = frozenset(
    {DOWNLOAD_STATUS_SKIPPED, DOWNLOAD_STATUS_RESUMABLE, DOWNLOAD_STATUS_UNKNOWN}
)

# --- Person roles (per schema spec) ---
PERSON_ROLE_UPLOADER = "UPLOADER"
PERSON_ROLE_AUTHOR = "AUTHOR"
PERSON_ROLE_OWNER = "OWNER"
PERSON_ROLE_OTHER = "OTHER"
PERSON_ROLE_UNKNOWN = "UNKNOWN"

# Back-compat aliases for legacy call sites.
PERSON_ROLE_CREATOR = PERSON_ROLE_AUTHOR
PERSON_ROLE_CONTRIBUTOR = PERSON_ROLE_OTHER
PERSON_ROLE_SUPERVISOR = PERSON_ROLE_OTHER

# --- Download methods ---
DOWNLOAD_METHOD_API = "API-CALL"
DOWNLOAD_METHOD_SCRAPING = "SCRAPING"

# --- Repository IDs (from Qualitative Data Repositories list) ---
REPO_ID_ZENODO = 1
REPO_ID_DRYAD = 2
REPO_ID_UK_DATA_SERVICE = 3
REPO_ID_SYRACUSE_QDR = 4
REPO_ID_DANS = 5
REPO_ID_DATAVERSE_NO = 6
REPO_ID_ADA = 7
REPO_ID_SADA = 8
REPO_ID_HIHSN = 9
REPO_ID_HARVARD_DATAVERSE = 10

# --- Run modes ---
RUN_MODE_INCREMENTAL = "incremental"
RUN_MODE_FULL = "full"

DEFAULT_CHUNK_SIZE_BYTES = 4 * 1024 * 1024
